version: '3.7'
services:
  server_1:
    image: gcr.io/google_containers/echoserver:1.8
    container_name: server_1
  server_2:
    image: gcr.io/google_containers/echoserver:1.8
    container_name: server_2
  server_3:
    image: gcr.io/google_containers/echoserver:1.8
    container_name: server_3
  load_balance:
      image: nginx:alpine
      container_name: load_balance
      ports:
        - "3000:80"
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf
        - ./default.conf:/etc/nginx/conf.d/default.conf